FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /loadbalancer ./cmd/loadbalancer/main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /loadbalancer /loadbalancer
COPY config/config.docker.json /app/config/config.json
COPY web/dashboard.html /app/web/dashboard.html
ENTRYPOINT ["/loadbalancer"]
