FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /backend ./backend/server.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /backend /backend
ENTRYPOINT ["/backend"]
